name: .NET Core CI

on:
  release:
    types: [published]

jobs:
  build:
    name: .NET on ${{ matrix.runs-on }} (${{ matrix.configuration }})
    runs-on: ${{ matrix.runs-on }}
    permissions:
      contents: write
    strategy:
      fail-fast: false
      matrix:
        runs-on: [ubuntu-latest]
        configuration: [Release]
    env:
      DOTNET_CLI_TELEMETRY_OPTOUT: 1
    steps:
      - uses: actions/checkout@v3

      - name: Setup .NET Core
        uses: actions/setup-dotnet@v2
        with:
          dotnet-version: 7.0.x

      - name: Build
        run: dotnet publish -c ${{ matrix.configuration }} -r win-x64 -o artifacts

      - name: Upload artifact
        uses: actions/upload-artifact@v3
        if: matrix.configuration == 'Release'
        with:
          name: DepotDownloader-${{ runner.os }}-framework
          path: artifacts
          if-no-files-found: error

      - name: Publish Windows-x64
        run: dotnet publish --configuration Release -p:PublishSingleFile=true -p:DebugType=embedded --self-contained --runtime win-x64 --output selfcontained-win-x64

      - name: Upload Windows-x64
        run:
          gh release upload ${GITHUB_REF##*/} selfcontained-win-x64/DepotDownloader.exe
        env:
          GH_TOKEN: ${{ github.token }}
          GH_REF: ${{ github.ref }}
